# Generated by Django 4.1.4 on 2023-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellingpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
