# Generated by Django 4.1.4 on 2023-01-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selling", "0002_alter_sellingpost_title"),
    ]

    operations = [
        migrations.AlterModelOptions(name="sellingpost", options={},),
        migrations.RemoveField(model_name="sellingpost", name="seller",),
    ]
