# Generated by Django 4.1.4 on 2023-01-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("selling", "0003_alter_sellingpost_options_remove_sellingpost_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellingpost",
            name="seller",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
